/* Permanent recipe library; local search and favorites, original six-serving quantities. */
let kitchenQuery='',kitchenScope='edition',kitchenQuick=false,kitchenSavedOnly=false;
let kitchenLibrary=[],kitchenLoading=false,kitchenLoadError=false;
const kitchenFavorites=new Set((()=>{try{const saved=JSON.parse(localStorage.getItem('real-kitchen-favorites')||'[]');return Array.isArray(saved)?saved:[]}catch{return []}})());
const kitchenKey=r=>r._date+'|'+r.title;
function kitchenCatalog(){const edition=KITCHEN_EDITION||DATA.kitchen;const rows=kitchenScope==='library'?kitchenLibrary:(edition?.recipes||FAMILY_RECIPES).map((r,i)=>({...r,_date:edition?.date,_index:i+1}));const terms=kitchenQuery.toLowerCase().trim().split(/\s+/).filter(Boolean);return rows.filter(r=>{const text=[r.title,r.cuisine,r.meal,...r.ingredients.map(i=>i.name)].join(' ').toLowerCase();return terms.every(t=>text.includes(t))&&(!kitchenQuick||r.prep+r.cook<=30)&&(!kitchenSavedOnly||kitchenFavorites.has(kitchenKey(r)))})}
function kitchenTools(){return `<section class="kitchen-tools" aria-label="Find a recipe"><h2>What shall we cook?</h2><div class="kitchen-search"><label>Search by dish or ingredient<input id="kitchen-query" type="search" placeholder="Try chicken, tofu, Japanese…" value="${escapeHTML(kitchenQuery)}"></label><label>Search in<select id="kitchen-scope"><option value="edition" ${kitchenScope==='edition'?'selected':''}>Selected daily edition</option><option value="library" ${kitchenScope==='library'?'selected':''}>All saved recipes</option></select></label></div><div class="kitchen-toggles"><label><input type="checkbox" id="kitchen-quick" ${kitchenQuick?'checked':''}> 30 minutes or less (prep + cook)</label><label><input type="checkbox" id="kitchen-saved" ${kitchenSavedOnly?'checked':''}> My saved recipes</label></div><p class="fine" role="status">${kitchenLoading?'Loading the recipe archive…':kitchenScope==='library'?`${kitchenLibrary.length} archived recipes loaded. `:''}${kitchenLoadError?'Some dates could not load. <button class="listen" data-kitchen-retry>Retry archive</button>':''}Download a complete one-page Letter PDF, or open it to print. Saved recipes stay on this device.</p></section>`}
async function loadKitchenLibrary(){if(kitchenLoading)return;kitchenLoading=true;kitchenLoadError=false;if(location.hash==='#recipes')render();const dates=[...new Set([...(DAILY_HISTORY.recipes||[]),DATA.kitchen?.date].filter(Boolean))];const results=await Promise.allSettled(dates.map(async date=>{const response=await fetch('data/recipes-archive/'+date+'.json');if(!response.ok)throw Error();const e=await response.json();return e.recipes.map((r,i)=>({...r,_date:e.date,_index:i+1}))}));kitchenLibrary=results.filter(r=>r.status==='fulfilled').flatMap(r=>r.value).sort((a,b)=>b._date.localeCompare(a._date));kitchenLoadError=results.some(r=>r.status==='rejected');kitchenLoading=false;if(location.hash==='#recipes')render()}
function recipePdf(r){return `data/recipe-pdfs/${r._date}/${encodeURIComponent('Family Kitchen_'+r._date+'_'+String(r._index).padStart(2,'0')+'.pdf')}`}
function recipeActions(r){if(!r._date)return '';const name='Family Kitchen_'+r._date+'_'+String(r._index).padStart(2,'0')+'.pdf';return `<div class="recipe-actions"><a class="listen" href="${recipePdf(r)}" download="${escapeHTML(name)}">↓ Download PDF</a><a class="listen" href="${recipePdf(r)}" target="_blank" rel="noopener" aria-label="Open ${escapeHTML(r.title)} as Letter PDF to print">▧ Print</a><button class="listen" data-kitchen-save="${escapeHTML(kitchenKey(r))}" aria-pressed="${kitchenFavorites.has(kitchenKey(r))}">${kitchenFavorites.has(kitchenKey(r))?'♥ Saved':'♡ Save recipe'}</button></div>`}
let kitchenTyping;
document.addEventListener('input',event=>{if(event.target.id!=='kitchen-query')return;kitchenQuery=event.target.value;clearTimeout(kitchenTyping);kitchenTyping=setTimeout(()=>{if(location.hash!=='#recipes')return;render();const input=document.querySelector('#kitchen-query');input?.focus()},250)});
document.addEventListener('change',event=>{const id=event.target.id;if(id==='kitchen-scope'){kitchenScope=event.target.value;if(kitchenScope==='library'&&!kitchenLibrary.length){loadKitchenLibrary();return}}else if(id==='kitchen-quick')kitchenQuick=event.target.checked;else if(id==='kitchen-saved')kitchenSavedOnly=event.target.checked;else return;render()});
document.addEventListener('click',event=>{const save=event.target.closest('[data-kitchen-save]');if(save){const key=save.dataset.kitchenSave;kitchenFavorites.has(key)?kitchenFavorites.delete(key):kitchenFavorites.add(key);localStorage.setItem('real-kitchen-favorites',JSON.stringify([...kitchenFavorites]));render()}if(event.target.closest('[data-kitchen-retry]'))loadKitchenLibrary()});
