/* Render complete English lesson posters locally; no account or upload needed. */
const CARD_COLORS={red:'#b82c30',orange:'#ad5018',yellow:'#926a0c',green:'#1c5840',blue:'#244890',purple:'#503773',black:'#25272c'};
const cardFiles=new Map();
function currentEdition(){return SELECTED_EDITION||DATA.english}
function activeLessons(){const daily=currentEdition()?.lessons;return daily?.length?daily.map(l=>({...LESSONS.find(base=>base.image===l.image),...l})):LESSONS.map(l=>({...l,id:l.image}))}
function cardKey(lesson){return `${currentEdition()?.date||'preview'}-${lesson.image}-${lesson.title}-${currentEdition()?.revision||1}`}
function wrapCardText(ctx,text,width){const lines=[];for(const paragraph of text.split('\n')){let line='';for(const word of paragraph.split(/\s+/)){const candidate=line?line+' '+word:word;if(ctx.measureText(candidate).width>width&&line){lines.push(line);line=word}else line=candidate}lines.push(line)}return lines}
async function makeCardFile(lesson){const key=cardKey(lesson);if(cardFiles.has(key))return cardFiles.get(key);const promise=(async()=>{const date=currentEdition()?.date;if(!date||!lesson.id)throw Error('No dated card available');const response=await fetch(`data/english-images/${date}/${lesson.id}.png?revision=${currentEdition()?.revision||1}`,{cache:'no-cache'});if(!response.ok)throw Error('Card image unavailable');const blob=await response.blob();if(!blob.type.startsWith('image/'))throw Error('Invalid card image');return new File([blob],`real-family-${lesson.id}.png`,{type:'image/png'})})();cardFiles.set(key,promise);promise.catch(()=>cardFiles.delete(key));return promise}

function downloadCard(file){const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;a.download=file.name;document.body.append(a);a.click();a.remove();let preview=document.querySelector('#card-preview');if(preview)preview.remove();preview=document.createElement('dialog');preview.id='card-preview';preview.innerHTML='<button type="button" class="button" aria-label="Close card preview">Close</button><p class="fine">Your complete card · On mobile, touch and hold the image to save it.</p><img alt="Exported English learning card"><p><a class="button">Download PNG</a></p>';preview.querySelector('img').src=url;const link=preview.querySelector('a');link.href=url;link.download=file.name;preview.querySelector('button').onclick=()=>{preview.close();preview.remove();URL.revokeObjectURL(url)};document.body.append(preview);preview.showModal()}
async function exportLesson(button,action){const lesson=activeLessons().find(l=>l.id===button.dataset.value);if(!lesson)return;const label=button.textContent;button.disabled=true;button.textContent='Preparing…';const status=document.querySelector('#card-status');try{const file=await makeCardFile(lesson);if(action==='share-card'&&navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:lesson.title,text:'A little English, every day — Real Family'});status.textContent='Card shared.'}else{downloadCard(file);status.textContent=action==='share-card'?'Image downloaded. Attach it in your preferred chat app.':'PNG image downloaded. On mobile, use your browser’s save options.'}}catch(error){if(error.name!=='AbortError')status.textContent='The card could not be saved. Please try again.'}finally{button.disabled=false;button.textContent=label}}
document.addEventListener('click',event=>{const button=event.target.closest('[data-action="share-card"],[data-action="save-card"]');if(button)exportLesson(button,button.dataset.action)});
function preloadCardExports(){for(const lesson of activeLessons())makeCardFile(lesson).catch(()=>{})}
