/* Complete portrait cards: iPhone 17 Pro Max, screen ratio, lightweight 660 × 1434 pixels. */
const fs=require('fs'),path=require('path');
const sharp=require(process.env.REAL_FAMILY_SHARP||'/Users/jr/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root=path.resolve(__dirname,'..'),date=process.argv[2],edition=JSON.parse(fs.readFileSync(fs.existsSync(path.join(root,'data/english-archive',date+'.json'))?path.join(root,'data/english-archive',date+'.json'):path.join(root,'data/english-staged',date+'.json'))),out=path.join(root,'data/english-images',date);fs.mkdirSync(out,{recursive:true});
const colors={vocabulary:'#b82c30',phrasal:'#ad5018',idiom:'#926a0c',life:'#1c5840',grammar:'#244890',quote:'#503773','small-talk':'#25272c'},labels={vocabulary:'Vocabulary',phrasal:'Phrasal verbs',idiom:'Idioms & slang',life:'Life phrases',grammar:'Grammar',quote:'Quote','small-talk':'Small talk'};
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const {createCanvas,GlobalFonts}=require(process.env.REAL_FAMILY_CANVAS||'/Users/jr/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');
for(const file of ['Arial.ttf','Arial Bold.ttf']){const font='/System/Library/Fonts/Supplemental/'+file;if(fs.existsSync(font))GlobalFonts.registerFromPath(font,'Arial');}
const measure=createCanvas(1,1).getContext('2d'),margin=56,textWidth=1320-margin*2;
function wrap(text,size,bold){measure.font=`${bold?'bold ':''}${size}px Arial`;const lines=[];for(const paragraph of text.split('\n')){let line='';for(const word of paragraph.split(/\s+/)){const next=(line+' '+word).trim();if(measure.measureText(next).width>textWidth-8&&line){lines.push(line);line=word}else line=next}lines.push(line)}return lines}
function layout(l,scale,leading=1.3){let y=925,parts=[],bounds=[];const put=(text,size,bold=false,gap=24)=>{size=Math.round(size*scale);for(const line of wrap(text,size,bold)){measure.font=`${bold?'bold ':''}${size}px Arial`;const width=measure.measureText(line).width;bounds.push({text:line,width,size,y});parts.push(`<text x="${margin}" y="${y}" fill="white" font-family="Arial" font-size="${size}" ${bold?'font-weight="bold"':''}>${escape(line)}</text>`);y+=size*leading}y+=gap*scale};put(l.title,82,true,34);for(const [label,value] of [['MEANING',l.meaning],['IN CONTEXT',l.example],['USAGE NOTE',l.notes],['CONVERSATION',l.conversation],['YOUR TURN',l.exercise]]){put(label,30,true,8);put(value,48,false,30)}return {parts,y,bounds}}
function fit(l){let best=null;for(let scale=.73;scale<=1.401;scale+=.01){const body=layout(l,scale);if(body.y<=2670)best={...body,scale}}if(!best)throw Error('Lesson is too long for a readable screen card: '+l.title);for(let leading=1.31;leading<=1.421;leading+=.01){const roomier=layout(l,best.scale,leading);if(roomier.y<=2670)best={...roomier,scale:best.scale}}if(best.bounds.some(b=>b.width>textWidth))throw Error('Text exceeds card width: '+l.title);return best}
(async()=>{for(const l of edition.lessons.filter(l=>!process.argv[3]||l.id===process.argv[3])){if(!l.illustration)throw Error('Missing topic illustration: '+l.title);const body=fit(l),scale=body.scale;const illustration=await sharp(path.join(root,l.illustration)).resize(textWidth,620,{fit:'cover'}).png().toBuffer();const parts=[`<text x="${margin}" y="110" fill="white" font-family="Arial" font-size="30" font-weight="bold">REAL FAMILY / EVERYDAY ENGLISH</text>`,`<image x="${margin}" y="160" width="${textWidth}" height="620" href="data:image/png;base64,${illustration.toString('base64')}"/>`,`<text x="${margin}" y="820" fill="white" font-family="Arial" font-size="30" font-weight="bold">${escape(labels[l.image].toUpperCase())} · ${escape(l.level||'B2–C1')}</text>`,...body.parts,`<text x="${margin}" y="2740" fill="white" font-family="Arial" font-size="30">${date} · PT</text>`,`<text x="${margin}" y="2790" fill="white" font-family="Arial" font-size="30">TopChainFresh.com/realfamily/</text>`];const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1320" height="2868"><rect width="100%" height="100%" fill="${colors[l.image]}"/>${parts.join('')}</svg>`;await sharp(Buffer.from(svg)).resize(660,1434).png({palette:true,colours:256,effort:7}).toFile(path.join(out,l.id+'.png'));console.log(l.id,'660 × 1434','font scale',scale.toFixed(2),'bottom',Math.round(body.y))}})().catch(e=>{console.error(e);process.exit(1)});
