/* Complete portrait cards: iPhone 17 Pro Max, 1320 × 2868 pixels. */
const fs=require('fs'),path=require('path');
const sharp=require(process.env.REAL_FAMILY_SHARP||'/Users/jr/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root=path.resolve(__dirname,'..'),date=process.argv[2],edition=JSON.parse(fs.readFileSync(path.join(root,'data/english-archive',date+'.json'))),out=path.join(root,'data/english-images',date);fs.mkdirSync(out,{recursive:true});
const colors={vocabulary:'#b82c30',phrasal:'#ad5018',idiom:'#926a0c',life:'#1c5840',grammar:'#244890',quote:'#503773','small-talk':'#25272c'},labels={vocabulary:'Vocabulary',phrasal:'Phrasal verbs',idiom:'Idioms & slang',life:'Life phrases',grammar:'Grammar',quote:'Quote','small-talk':'Small talk'};
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
function wrap(text,n){let lines=[];for(const paragraph of text.split('\n')){let line='';for(const word of paragraph.split(/\s+/)){if((line+' '+word).trim().length>n&&line){lines.push(line);line=word}else line=(line+' '+word).trim()}lines.push(line)}return lines}
function layout(l,scale){let y=930,parts=[];const put=(text,size,bold=false,gap=24)=>{size=Math.round(size*scale);for(const line of wrap(text,Math.floor(1128/(size*.60)))){parts.push(`<text x="96" y="${y}" fill="white" font-family="Arial" font-size="${size}" ${bold?'font-weight="bold"':''}>${escape(line)}</text>`);y+=size*1.38}y+=gap*scale};put(l.title,82,true,34);for(const [label,value] of [['MEANING',l.meaning],['IN CONTEXT',l.example],['USAGE NOTE',l.notes],['CONVERSATION',l.conversation],['YOUR TURN',l.exercise]]){put(label,30,true,8);put(value,48,false,30)}return {parts,y}}
(async()=>{for(const l of edition.lessons){if(!l.illustration)throw Error('Missing topic illustration: '+l.title);let scale=1,body=layout(l,scale);while(body.y>2640&&scale>.73){scale-=.025;body=layout(l,scale)}if(body.y>2640)throw Error('Lesson is too long for a readable screen card: '+l.title);const illustration=await sharp(path.join(root,l.illustration)).resize(1128,620,{fit:'cover'}).png().toBuffer();const parts=[`<text x="96" y="110" fill="white" font-family="Arial" font-size="30" font-weight="bold">REAL FAMILY / EVERYDAY ENGLISH</text>`,`<image x="96" y="160" width="1128" height="620" href="data:image/png;base64,${illustration.toString('base64')}"/>`,`<text x="96" y="820" fill="white" font-family="Arial" font-size="30" font-weight="bold">${escape(labels[l.image].toUpperCase())} · B2–C1</text>`,...body.parts,`<text x="96" y="2740" fill="white" font-family="Arial" font-size="30">${date} · Pacific Time</text>`,`<text x="96" y="2790" fill="white" font-family="Arial" font-size="30">TopChainFresh.com/realfamily/</text>`];const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1320" height="2868"><rect width="100%" height="100%" fill="${colors[l.image]}"/>${parts.join('')}</svg>`;await sharp(Buffer.from(svg)).png({palette:true,colours:256,effort:7}).toFile(path.join(out,l.id+'.png'));console.log(l.id,'1320 × 2868','font scale',scale.toFixed(2),'bottom',Math.round(body.y))}})().catch(e=>{console.error(e);process.exit(1)});
