const COUNTRIES=[['US','United States','🇺🇸'],['TW','Taiwan','🇹🇼'],['GB','United Kingdom','🇬🇧'],['JP','Japan','🇯🇵'],['CN','China','🇨🇳'],['IN','India','🇮🇳'],['DE','Germany','🇩🇪'],['FR','France','🇫🇷'],['KR','South Korea','🇰🇷'],['CA','Canada','🇨🇦']];
const MARKETS=[
['United States','America/New_York','16:00','USD',[['Dow Jones','^DJI'],['NASDAQ Composite','^IXIC'],['S&P 500','^GSPC'],['Philadelphia Semiconductor','^SOX'],['Russell 2000','^RUT']]],
['China','Asia/Shanghai','15:00','CNY',[['Shanghai Composite','000001.SS'],['Shenzhen Component','399001.SZ'],['CSI 300','000300.SS'],['STAR 50','000688.SS'],['ChiNext','399006.SZ']]],
['Japan','Asia/Tokyo','15:30','JPY',[['Nikkei 225','^N225'],['TOPIX','^TOPX']]],
['India','Asia/Kolkata','15:30','INR',[['NIFTY 50','^NSEI'],['SENSEX','^BSESN'],['NIFTY Bank','^NSEBANK']]],
['Hong Kong','Asia/Hong_Kong','16:00','HKD',[['Hang Seng','^HSI'],['Hang Seng China Enterprises','^HSCE'],['Hang Seng TECH','HSTECH.HK']]],
['Canada','America/Toronto','16:00','CAD',[['S&P/TSX Composite','^GSPTSE'],['S&P/TSX 60','TX60.TS']]],
['United Kingdom','Europe/London','16:30','GBP',[['FTSE 100','^FTSE'],['FTSE 250','^FTMC'],['FTSE All-Share','^FTAS']]],
['France','Europe/Paris','17:30','EUR',[['CAC 40','^FCHI'],['SBF 120','^SBF120']]],
['Germany','Europe/Berlin','17:30','EUR',[['DAX','^GDAXI'],['MDAX','^MDAXI'],['SDAX','^SDAXI'],['TecDAX','^TECDAX']]],
['Taiwan','Asia/Taipei','13:30','TWD',[['TAIEX','^TWII'],['Taipei Exchange Index','^TWOII']]],
['South Korea','Asia/Seoul','15:30','KRW',[['KOSPI','^KS11'],['KOSDAQ','^KQ11']]],
['Australia','Australia/Sydney','16:00','AUD',[['S&P/ASX 200','^AXJO'],['All Ordinaries','^AORD']]],
['Saudi Arabia','Asia/Riyadh','15:00','SAR',[['Tadawul All Share','^TASI.SR']]],
['Switzerland','Europe/Zurich','17:30','CHF',[['Swiss Market Index','^SSMI'],['Swiss Performance Index','^SPI']]]
];
const LESSONS=[
{color:'red',category:'Vocabulary',title:'perfunctory',image:'vocabulary',inset:true,meaning:'Done quickly with little care or attention.',example:'She gave the proposal a perfunctory glance before returning it.',notes:'Adjective · /pərˈfʌŋktəri/ · Similar words: cursory, half-hearted, superficial.',conversation:'A: Did he give you useful feedback?\nB: Just a perfunctory nod. I was hoping for more detail.',exercise:'Try it: Describe a task someone completed without much effort.'},
{color:'orange',category:'Phrasal verbs',title:'work out',image:'phrasal',inset:true,meaning:'To develop successfully; also, to exercise or solve a problem.',example:'Despite the setbacks, the move worked out well for them.',notes:'Worked out · working out. “Work out a plan” means develop or solve it.',conversation:'A: I am nervous about the interview.\nB: You have prepared well. I hope it works out!',exercise:'Try it: Write a sentence about a plan that succeeded.'},
{color:'yellow',category:'Idioms & slang',title:'the tip of the iceberg',image:'idiom',inset:true,meaning:'The small, visible part of something much larger.',example:'These delays are only the tip of the iceberg.',notes:'Often used when a problem has more hidden details. Informal: “That is just the beginning.”',conversation:'A: Were those the only issues?\nB: No, that was just the tip of the iceberg.',exercise:'Try it: What could be the hidden part of a problem?'},
{color:'green',category:'Life phrases',title:'One thing at a time.',image:'life',meaning:'Focus on one task before moving to the next.',example:'I have a lot to do today, so I am taking it one thing at a time.',notes:'A reassuring phrase when someone feels overwhelmed.',conversation:'A: My to-do list is endless.\nB: Take it one thing at a time. What matters most today?',exercise:'Try it: Use this phrase to reassure a friend.'},
{color:'blue',category:'Grammar',title:'Gerund or infinitive?',image:'grammar',meaning:'Some verbs take -ing; others take to + the base verb.',example:'I enjoy swimming. I hope to swim tomorrow.',notes:'Enjoy, avoid, finish + -ing. Want, decide, hope + to. “Stop smoking” means quit; “stop to smoke” means pause another activity.',conversation:'A: Are you planning to join the class?\nB: Yes! I enjoy learning new skills.',exercise:'Try it: Complete “I enjoy ___” and “I hope to ___”.'},
{color:'purple',category:'Quote',title:'“Well done is better than well said.”',image:'quote',meaning:'Actions matter more than promises or impressive words.',example:'Instead of describing her plans, she took the first step.',notes:'Benjamin Franklin · Poor Richard’s Almanack, 1737. “Well done” means performed successfully.',conversation:'A: I keep talking about studying English.\nB: Start with ten minutes today. Actions count.',exercise:'Try it: What small action could you take today?'},
{color:'black',category:'Small talk',title:'How has work been treating you?',image:'small-talk',inset:true,meaning:'A friendly way to ask how someone feels about their work lately.',example:'How has work been treating you this week?',notes:'Relaxed and conversational. Follow up with an open question and share your own experience.',conversation:'A: How has work been treating you?\nB: Pretty well. We just wrapped up a project.\nA: That is great! Anything exciting coming next?\nB: A quieter week, hopefully. How about you?',exercise:'Try it: Ask the question, then practice a friendly follow-up.'}
];
const CUISINES=['American','European','Japanese','Mediterranean','Chinese','Taiwanese','Hong Kong','Korean','Indian','Seasonal'];
const RECIPES=[
['American','Main','Lemon herb chicken','🍋',30,'2 chicken breasts; 1 tbsp olive oil; 1 lemon; 1 tsp dried herbs; 2 cups broccoli','Heat oven to 425°F / 220°C.|Coat chicken and broccoli with oil, lemon juice and herbs.|Roast until the chicken reaches 165°F / 74°C, about 20–25 minutes. Rest 5 minutes.','Poultry'],
['American','Snack','Peanut butter apple bites','🍎',10,'1 apple; 2 tbsp peanut butter; 2 tbsp oats','Wash, core and slice the apple.|Spread peanut butter on each slice.|Sprinkle with oats and serve.','Peanuts'],
['European','Main','Tomato basil pasta','🍝',25,'200 g pasta; 400 g canned tomatoes; 2 garlic cloves; 1 tbsp olive oil; basil','Boil pasta according to the package.|Cook chopped garlic in oil for 1 minute; add tomatoes and simmer 10 minutes.|Toss pasta with sauce and basil.','Wheat'],
['European','Snack','Berry yogurt parfait','🫐',10,'1 cup plain yogurt; 1 cup berries; ¼ cup granola','Wash the berries.|Layer yogurt, berries and granola in two glasses.|Serve immediately.','Milk; granola may contain nuts or wheat'],
['Japanese','Main','Ginger salmon rice bowl','🍚',25,'2 salmon fillets; 2 cups cooked rice; 1 tsp grated ginger; 1 tbsp soy sauce; 1 cucumber','Heat oven to 400°F / 200°C.|Brush salmon with soy sauce and ginger; bake until 145°F / 63°C, about 12–15 minutes.|Serve over rice with sliced cucumber.','Fish; soy; wheat in some soy sauces'],
['Japanese','Snack','Sesame edamame','🫛',10,'2 cups frozen edamame; 1 tsp sesame oil; 1 tsp sesame seeds','Boil edamame according to package instructions.|Drain and toss with sesame oil.|Sprinkle with sesame seeds; eat the beans, discard pods.','Soy; sesame'],
['Mediterranean','Main','Chickpea vegetable bowl','🥗',20,'400 g canned chickpeas; 1 cucumber; 2 tomatoes; 2 tbsp olive oil; 1 lemon; parsley','Drain and rinse chickpeas.|Dice the vegetables and mix with chickpeas.|Dress with oil, lemon juice and chopped parsley.','None in listed ingredients'],
['Mediterranean','Snack','Lemony hummus','🫘',10,'400 g canned chickpeas; 2 tbsp tahini; 1 lemon; 1 garlic clove; 2 tbsp water','Drain and rinse chickpeas.|Blend with tahini, lemon juice, garlic and water.|Serve with sliced vegetables.','Sesame'],
['Chinese','Main','Tofu and vegetable stir-fry','🥬',20,'300 g firm tofu; 2 cups mixed vegetables; 1 tbsp oil; 1 tbsp soy sauce; 1 tsp ginger','Drain tofu and cut into cubes.|Brown tofu in oil; add vegetables and ginger and stir-fry until tender.|Add soy sauce and serve with cooked rice.','Soy; wheat in some soy sauces'],
['Chinese','Snack','Steamed sweet potato','🍠',25,'2 small sweet potatoes; water','Wash and cut potatoes into thick rounds.|Steam over boiling water for 20 minutes or until fork-tender.|Let cool slightly before serving.','None in listed ingredients'],
['Taiwanese','Main','Three-cup mushroom chicken','🍲',30,'300 g boneless chicken; 200 g mushrooms; 1 tbsp sesame oil; 1 tbsp soy sauce; 2 tbsp rice wine; ginger; basil','Brown ginger and chicken in sesame oil.|Add mushrooms, soy sauce and rice wine; cover and simmer.|Cook chicken to 165°F / 74°C. Stir in basil and serve.','Soy; sesame; wheat in some soy sauces'],
['Taiwanese','Snack','Scallion egg pancake','🥞',15,'1 ready-made scallion pancake; 1 egg; 1 chopped scallion; 1 tsp oil','Pan-fry pancake according to package instructions.|Beat egg with scallion; pour into a lightly oiled pan.|Place pancake on egg and cook until egg is set; roll and cut.','Wheat; egg'],
['Hong Kong','Main','Tomato egg rice','🍅',20,'3 eggs; 3 tomatoes; 1 tsp oil; 2 cups cooked rice; 2 tbsp water','Beat eggs and scramble in oil until set; remove.|Cook chopped tomatoes with water until softened.|Return eggs to pan, heat through and serve over rice.','Egg'],
['Hong Kong','Snack','Mango coconut cups','🥭',10,'1 mango; ½ cup coconut yogurt; 2 tbsp shredded coconut','Peel and dice mango.|Spoon yogurt into two cups; add mango.|Top with shredded coconut and chill.','Coconut; check yogurt label'],
['Korean','Main','Vegetable bibimbap','🥕',25,'2 cups cooked rice; 1 carrot; 1 cup spinach; 100 g mushrooms; 2 eggs; 1 tbsp gochujang','Slice and sauté vegetables separately until tender.|Cook eggs until whites and yolks are firm.|Arrange over rice and add gochujang to taste.','Egg; soy and wheat may be in gochujang'],
['Korean','Snack','Mini vegetable pancakes','🧅',20,'½ cup flour; ½ cup water; 1 cup shredded vegetables; 1 tbsp oil','Whisk flour and water; fold in vegetables.|Spoon small portions into an oiled skillet.|Cook 3–4 minutes per side until golden and fully cooked.','Wheat'],
['Indian','Main','Red lentil dal','🍛',30,'1 cup red lentils; 3 cups water; 1 tomato; 1 tsp turmeric; 1 tsp cumin; 1 tbsp oil','Rinse lentils and simmer in water with turmeric until soft.|Cook cumin and chopped tomato in oil for 5 minutes.|Stir into lentils; simmer 5 minutes and serve with rice.','None in listed ingredients'],
['Indian','Snack','Cucumber raita','🥒',10,'1 cup plain yogurt; ½ cucumber; ¼ tsp cumin; mint','Wash, grate and gently squeeze cucumber.|Mix into yogurt with cumin and mint.|Chill until serving; keep refrigerated.','Milk'],
['Seasonal','Main','Autumn squash tray bake','🎃',40,'500 g squash; 400 g canned chickpeas; 1 red onion; 2 tbsp olive oil; rosemary','Heat oven to 425°F / 220°C; peel and cube squash.|Toss squash, drained chickpeas and sliced onion with oil and rosemary.|Roast 30–35 minutes, stirring halfway, until squash is tender.','None in listed ingredients'],
['Seasonal','Snack','Warm cinnamon pears','🍐',20,'2 pears; ½ tsp cinnamon; 2 tbsp water; 2 tbsp plain yogurt','Core and slice pears.|Simmer with cinnamon and water for 10–12 minutes until tender.|Serve warm with yogurt.','Milk if using dairy yogurt']
];
